apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-app-deploy
  labels:
    app: insurance-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insurance-app
  template:
    metadata:
      labels:
        app: insurance-app
    spec:
      containers:
      - name: insurance-container
        image: uday023/insurance-app
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-np-service
  labels:
    app: insurance-app
spec:
  selector:
    app: insurance-app
  type: NodePort
  ports:
  - nodePort: 31032  
    port: 8084
    targetPort: 8084
